config/routes.rb
FirstQuarterlyProject::Application.routes.draw do
  resources :members
  resources :classrooms
  resources :strengths
  resources :weaknesses
  get '/error' => 'members#error'
  post '/recommendations/new' => 'recommendations#create'
  post '/messages/new' => 'messages#create'
  post '/messages' => 'messages#destroy'
  post '/login' => 'main#connect'
  get '/logout' => 'main#logout'
  root :to => 'main#login'
end

app/views/layouts/_nav.html.erb
  <!-- Header and Nav -->

  <div class="fixed contain-to-grid">
    <nav class="top-bar">
      <ul>
        <li class="name"><h1><%= link_to("tppl", logout_path) %></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>
      <% if $user != nil %>
      <section>
        <ul class="left">
          <li><%= link_to("My Page", $user) %></li>
        </ul>
        <ul class="left">
          <li><%= link_to("My Class", members_path) %></li>
        </ul>
        <ul class="left">
          <li class="has-dropdown">
            <%= link_to("I Want Help With...", strengths_path) %>
            <ul class="dropdown">
              <% $user.weaknesses.each do |link| %>
                  <li><%= link_to(link.name, Strength.where(:name => link.name).first) %></li>
              <% end %>

            </ul>
          </li>
        </ul>
        <ul class="left">
          <li class="has-dropdown"><%= link_to("I Can Help With...", weaknesses_path) %>
            <ul class="dropdown">

              <% $user.strengths.each do |link| %>
                  <li><%= link_to(link.name, Weakness.where(:name => link.name).first) %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </section>
    <% end %>
    </nav>
  </div>

  <!-- End Header and Nav -->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>FirstQuarterlyProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>

  <%= render :partial => 'layouts/nav' %>

  <div class="main">
      <%= yield %>
  </div>

  <!-- Footer -->
<div class="gradient">
  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="six columns">
          <p>&copy; tppl.</p>
        </div>
        <div class="six columns">
          <ul class="link-list right">
            <li><a href="#">About</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</div>


  <script type="text/javascript">
     $(window).load(function() {
         $('#slider').orbit();
     });
  </script>

</body>
</html>