config/routes.rb
FirstQuarterlyProject::Application.routes.draw do
  resources :members
  resources :classrooms
  resources :strengths
  resources :weaknesses
  get '/error' => 'members#error'
  post '/recommendations/new' => 'recommendations#create'
  post '/messages/new' => 'messages#create'
  post '/messages' => 'messages#destroy'
  post '/login' => 'main#connect'
  get '/logout' => 'main#logout'
  root :to => 'main#login'
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id           :integer          not null, primary key
#  first        :string(255)
#  last         :string(255)
#  username     :string(255)
#  password     :string(255)
#  photo        :text
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  classroom_id :integer
#

class Member < ActiveRecord::Base
  attr_accessible :first, :last, :username, :photo, :description, :strength_ids, :weakness_ids, :classroom_id, :password
  has_and_belongs_to_many :strengths
  has_and_belongs_to_many :weaknesses
  has_many :recommendations
  has_many :messages
  belongs_to :classroom

  def full_name
    "#{first} #{last}"
  end

  def strength_check
    result = strengths.map(&:name).uniq
  end

  def weakness_check
    result = weaknesses.map(&:name).uniq
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = $classroom_members
  end

  def new
    @member = Member.new
  end

  def create
    username_check = params[:member]['first'] + params[:member]['last']

    if Member.where( :username => username_check.downcase ).present?
      redirect_to(error_path)
    else
      member = Member.create(params[:member])
      member.update_attributes( :password => 'welcome', :username => username_check.downcase)
      $classroom_members << member
      redirect_to(member)
    end

  end

  def show
    @member = $classroom_members.find(params[:id])
  end

  def edit
    @member = $classroom_members.find(params[:id])
  end

  def update
    member = Member.find(params[:id])

    if params[:member]['strength_ids'].present? && params[:member]['weakness_ids'].present?
      check = params[:member]['strength_ids'] & params[:member]['weakness_ids']
    else
      check = []
    end

    if check.count == 0
      member.update_attributes(params[:member])
      redirect_to(member)
    else
      redirect_to(error_path)
    end

  end

  def destroy
    member = Member.find(params[:id])
    member.delete
    redirect_to(members_path)
  end

  def error
  end

end

app/views/members/_form.html.haml
= form_for @member do |f|
  %input{ :name => :id, :type => 'hidden', :value => @member.id }
  = f.label :first
  = f.text_field :first
  = f.label :last
  = f.text_field :last
  = f.label :photo, "Image URL"
  = f.text_field :photo
  = f.label :description, "About you"
  = f.text_area :description, :rows => 3
  .row
    .six.columns
      %fieldset
        %legend I want help with...
        - Weakness.order(:name).each do |weakness|
          %p{ :class => 'left skill_checkboxes' }
            = weakness.name
            = check_box_tag 'member[weakness_ids][]', weakness.id, weakness.in?(@member.weaknesses)

    .six.columns
      %fieldset
        %legend I can help with...
        - Strength.order(:name).each do |strength|
          %p{ :class => 'left skill_checkboxes' }
            = strength.name
            = check_box_tag 'member[strength_ids][]', strength.id, strength.in?(@member.strengths)

  = f.submit 'Submit', :class => 'button'

app/views/members/_loveNote.html.erb
<!-- Call to Action Panel -->
  <div class="row">
    <div class="twelve columns" style="padding-top: 55px;">
        <h4>It's so good to see you.</h4>

        <div class="row">
          <div class="nine columns">
            <p><strong>tppl</strong> is an enclosed, peer to peer network where you can get and give help from others in your class. Encounter a problem? Please contact us and we'll get back to you as soon as possible.</p>
          </div>
          <div class="three columns">
            <a href="#" class="button right">Contact Us</a>
          </div>
        </div>
    </div>
  </div>

app/views/members/_subhead.html.haml
.row.hero_sub
  .twelve.columns
    %span
      %h1 Web Development Immersive, Celebrity Edition
      %h6 Your instructor is Chyld Medford

app/views/members/edit.html.haml
= render :partial => 'subhead'
.row
  .twelve.columns.card
    %h3 Edit Your Account
    = render :partial => 'form'

app/views/members/error.html.haml
%p Error! Stop trying to break my app.

app/views/members/index.html.haml
= render :partial => 'subhead'
.row
  - @members.each do |member|
    - if member.id != $user.id
      .four.columns.carriage
        .card
          .index_crop
            = link_to(image_tag(member.photo), member)
          .card_details
            %p
              %span{ :class => 'title'}= "#{member.full_name} - #{pluralize(member.recommendations.count, 'recommendation')}"
              = truncate(member.description, :length => 85)
            %h6= "I can help with..." if member.strengths.length > 0
            - member.strengths.each do |strength|
              %span{ :class => 'success label' }= strength.name
            %h6= "I'd like help with..." if member.weaknesses.length > 0
            - member.weaknesses.each do |weakness|
              %span{ :class => 'secondary label' }=weakness.name

app/views/members/new.html.haml
= render :partial => 'subhead'
.row
  .twelve.columns.card
    %h3 Create a New Member
    = render :partial => 'form'

app/views/members/show.html.haml
= render :partial => 'subhead'
.row
  .twelve.columns.carriage
    .row.card
      .four.columns
        .profile_crop
          = image_tag(@member.photo)
      .eight.columns
        .card_details
          %h2
            = @member.full_name
          = link_to('Edit My Profile', edit_member_path) if $user.id == @member.id
          %h5= @member.description
          %p
            = @member.first
            has received
            = pluralize(@member.recommendations.count, 'recommendation')
          %h6= "I can help with..." if @member.strengths.length > 0
          - @member.strengths.each do |strength|
            %span{ :class => 'success label' }= link_to(strength.name, strength)
          %h6= "I'd like help with..." if @member.weaknesses.length > 0
          - @member.weaknesses.each do |weakness|
            %span{ :class => 'secondary label' }=link_to(weakness.name, weakness)

.row{ :style => "padding-top: 20px;"}
  .twelve.columns
    .panel
      - @member.recommendations.each do |rec|
        %blockquote
          %p= rec.message
          %cite= link_to(Member.find(rec.recommender).full_name, Member.find(rec.recommender))
      - if @member.recommendations.present? == false
        %p No recommendations yet!
    - if $user != @member # THIS REMOVES THE MESSAGE BOX IF IT IS THE USER
      %h5= "Recommend #{@member.first}"
      %form{ :method => 'post', :action => '/recommendations/new'}
        %input{ :type => 'text', :name => 'message'}
        %input{ :type => 'hidden', :name => 'recommender', :value => $user.id }
        %input{ :type => 'hidden', :name => 'member_id', :value => @member.id }
        %button{ :class => 'small button'} Recommend!

- if ($user == @member) # THIS REMOVES THE LISTINGS UNLESS IT IS THE USER
  - if @member.weakness_check.count != 0
    .row{ :style => "padding-top: 10px;"}
      %h3 These people can help you:
      .twelve.columns
        .panel
          - Member.order(:first).each do |check|
            - if (check.username != @member.username)
              - helper_array = []
              - check.strengths.each do |str|
                - helper_array << str.name
              - if (helper_array & @member.weakness_check).count > 0
                = link_to(image_tag(check.photo, :class => 'thumb'), check)

- if $user == @member # THIS REMOVES THE MESSAGE BOX IF IT IS NOT THE USER
  - if @member.messages.present?
    .row{ :style => "padding-top: 10px;"}
      %h3 Your messages:
      - @member.messages.each do |m|
        .six.columns
          .panel
            .row
              .twelve.columns
                %h5= m.message
                - if m.message.exclude?("gmail")
                  %p
                    View profile:
                    = link_to(Member.find(m.from).full_name, Member.find(m.from))
                    %form{ :method => 'post', :action => '/messages'}
                      %input{ :type => 'hidden', :name => 'message_id', :value => m.id }
                      %input{ :type => 'hidden', :name => 'response', :value => 'yes' }
                      %button{ :class => 'success small button left', :style => "margin-right: 30px;"} Yes
                    %form{ :method => 'post', :action => '/messages'}
                      %input{ :type => 'hidden', :name => 'message_id', :value => m.id }
                      %input{ :type => 'hidden', :name => 'response', :value => 'no' }
                      %button{ :class => 'small button left'} No
                - if m.message.include?("gmail")
                  %form{ :method => 'post', :action => '/messages'}
                    %input{ :type => 'hidden', :name => 'message_id', :value => m.id }
                    %input{ :type => 'hidden', :name => 'response', :value => 'no' }
                    %button{ :class => 'small button left'} Delete

- if $user != @member # THIS REMOVES THE MESSAGE BOX IF IT IS THE USER
  .row{ :style => "padding-top: 20px;"}
    .twelve.columns
      .panel
        %h5= "Want to message #{@member.first}?"
        %form{ :method => 'post', :action => '/messages/new'}
          %input{ :type => 'hidden', :name => 'message', :value => "#{$user.full_name} would like to chat with you! Would you like to share your email?" }
          %input{ :type => 'hidden', :name => 'from', :value => $user.id }
          %input{ :type => 'hidden', :name => 'member_id', :value => @member.id }
          - if @member.messages.map(&:from).include?($user.id)
            %p= "Your message has been sent! #{@member.first} will respond if available."
          - else
            %button{ :class => 'small button'} Request Email